//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFramework.Statics
{
    
    public class Activity_btn_arrow
    {
        public const string BundleName = "activity_btn_arrow";
        public const string activity_btn_arrow_png = "activity_btn_arrow";
    }
    public class Arts
    {
        public const string BundleName = "arts";
    }
    public class Battle_sf
    {
        public const string BundleName = "battle.sf";
        public const string ArrowBody_prefab = "ArrowBody";
        public const string ArrowHead_prefab = "ArrowHead";
        public const string BattleView_prefab = "BattleView";
    }
    public class Effect_sf
    {
        public const string BundleName = "effect.sf";
        public const string FlashCard_mat = "FlashCard";
        public const string FlashCard_shader = "FlashCard";
        public const string FlashCard1_mat = "FlashCard1";
        public const string FlashCard1_shader = "FlashCard1";
    }
    public class Loading_sf
    {
        public const string BundleName = "loading.sf";
        public const string BarLoading_overrideController = "BarLoading";
        public const string BarLoading_prefab = "BarLoading";
        public const string BarLoadingEnd_anim = "BarLoadingEnd";
        public const string BarLoadingStart_anim = "BarLoadingStart";
        public const string BaseLoading_controller = "BaseLoading";
        public const string BaseLoading_prefab = "BaseLoading";
        public const string effect_jpg = "effect";
        public const string effect1_png = "effect1";
        public const string GameMainView_prefab = "GameMainView";
        public const string LoadingEnd_anim = "LoadingEnd";
        public const string LoadingStart_anim = "LoadingStart";
    }
    public class Modelavatar_sf
    {
        public const string BundleName = "model/avatar.sf";
        public const string Role_CarrotA_Appearance_FBX = "Role_CarrotA_Appearance";
        public const string Role_CarrotA_EatingIdle_FBX = "Role_CarrotA_EatingIdle";
        public const string Role_CarrotA_falldown_fbx = "Role_CarrotA_falldown";
        public const string Role_CarrotA_Feedback_fbx = "Role_CarrotA_Feedback";
        public const string Role_CarrotA_happy02_fbx = "Role_CarrotA_happy02";
        public const string Role_CarrotA_retreat_fbx = "Role_CarrotA_retreat";
        public const string Role_CarrotA_Story_Angry_FBX = "Role_CarrotA_Story_Angry";
        public const string Role_CarrotA_Story_Depressed_fbx = "Role_CarrotA_Story_Depressed";
        public const string Role_CarrotA_Story_Feedback_fbx = "Role_CarrotA_Story_Feedback";
        public const string Role_CarrotA_Story_Happy_fbx = "Role_CarrotA_Story_Happy";
        public const string Role_CarrotA_Story_Run_FBX = "Role_CarrotA_Story_Run";
        public const string Role_CarrotA_Story_Serious_FBX = "Role_CarrotA_Story_Serious";
        public const string Role_CarrotA_Story_Surprised_FBX = "Role_CarrotA_Story_Surprised";
        public const string Role_CarrotA_Story_Talk01_FBX = "Role_CarrotA_Story_Talk01";
        public const string Role_CarrotA_Story_Talk02_FBX = "Role_CarrotA_Story_Talk02";
        public const string Role_CarrotA_Story_Walk_FBX = "Role_CarrotA_Story_Walk";
        public const string Role_CarrotA_work_stone_FBX = "Role_CarrotA_work_stone";
        public const string Role_CarrotA_work_wood_FBX = "Role_CarrotA_work_wood";
        public const string Role_CarrotA_Attack_FBX = "Role_CarrotA_Attack";
        public const string Role_CarrotA_CasualState_FBX = "Role_CarrotA_CasualState";
        public const string Role_CarrotA_eat_fbx = "Role_CarrotA_eat";
        public const string Role_CarrotA_Hit_FBX = "Role_CarrotA_Hit";
        public const string Role_CarrotA_IdleState_FBX = "Role_CarrotA_IdleState";
        public const string Role_CarrotA_MoveState_FBX = "Role_CarrotA_MoveState";
        public const string Role_CarrotA_Skill_FBX = "Role_CarrotA_Skill";
        public const string Role_CarrotA_vertigo_fbx = "Role_CarrotA_vertigo";
        public const string Role_CarrotA_work_Cave_fbx = "Role_CarrotA_work_Cave";
        public const string Role_CarrotA_yuanditiao_fbx = "Role_CarrotA_yuanditiao";
        public const string Carrot_BaseColor_mat = "Carrot_BaseColor";
        public const string Carrot_BaseColor_png = "Carrot_BaseColor";
        public const string Role_mat = "Role";
        public const string Role_CarrotA_controller = "Role_CarrotA";
        public const string Role_CarrotA_Skin_FBX = "Role_CarrotA_Skin";
        public const string Role_CarrotA_Skin_prefab = "Role_CarrotA_Skin";
    }
    public class Modelmaterial_sf
    {
        public const string BundleName = "model/material.sf";
        public const string DirectionDissolve_shadergraph = "DirectionDissolve";
        public const string HoloGraphic_shadergraph = "HoloGraphic";
        public const string RimPower_shadergraph = "RimPower";
        public const string Role_shadergraph = "Role";
        public const string RoleBlinn_shader = "RoleBlinn";
        public const string RoleBlinnPhong_shader = "RoleBlinnPhong";
        public const string SimpleDissolve_shadergraph = "SimpleDissolve";
        public const string Test_shader = "Test";
    }
    public class Pic_sf
    {
        public const string BundleName = "pic.sf";
        public const string haipa_png = "haipa";
        public const string haipa_normal_png = "haipa_normal";
        public const string jusang_png = "jusang";
    }
    public class Scenesbasescene
    {
        public const string BundleName = "scenes/basescene";
        public const string BaseScene_unity = "BaseScene";
    }
    public class Sstest
    {
        public const string BundleName = "ss/test";
        public const string Test_prefab = "Test";
    }
}
