//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFramework.Statics
{
    
    public class SFResAssets
    {
        public const string Activity_btn_arrow_activity_btn_arrow_png = "activity_btn_arrow/activity_btn_arrow";
        public const string Battle_sf_ArrowBody_prefab = "battle.sf/ArrowBody";
        public const string Battle_sf_ArrowHead_prefab = "battle.sf/ArrowHead";
        public const string Battle_sf_BattleView_prefab = "battle.sf/BattleView";
        public const string Game_scenes_sf_BaseScene_unity = "game/scenes.sf/BaseScene";
        public const string Game_scenes_sf_BattleView_unity = "game/scenes.sf/BattleView";
        public const string Loading_sf_BarLoading_prefab = "loading.sf/BarLoading";
        public const string Loading_sf_BaseLoading_prefab = "loading.sf/BaseLoading";
        public const string Loading_sf_effect_jpg = "loading.sf/effect";
        public const string Loading_sf_effect1_png = "loading.sf/effect1";
        public const string Loading_sf_GameMainView_prefab = "loading.sf/GameMainView";
        public const string Model_avatar_role_carrota_sf_Carrot_BaseColor_png = "model/avatar/role_carrota.sf/Carrot_BaseColor";
        public const string Model_avatar_role_carrota_sf_Character_Carrot_prefab = "model/avatar/role_carrota.sf/Character_Carrot";
        public const string Model_avatar_role_carrota_sf_Role_CarrotA_Skin_prefab = "model/avatar/role_carrota.sf/Role_CarrotA_Skin";
        public const string Pic_sf_haipa_png = "pic.sf/haipa";
        public const string Pic_sf_haipa_normal_png = "pic.sf/haipa_normal";
        public const string Pic_sf_jusang_png = "pic.sf/jusang";
        public const string Pic_tree_sf_5101410_png = "pic/tree.sf/5101410";
        public const string Pic_tree_sf_5103524_png = "pic/tree.sf/5103524";
        public const string Pic_tree_sf_5104206_png = "pic/tree.sf/5104206";
        public const string Pic_tree_sf_5104309_png = "pic/tree.sf/5104309";
        public const string Pic_tree_sf_5104413_png = "pic/tree.sf/5104413";
        public const string Ss_test_Test_prefab = "ss/test/Test";
        public const string Texture_sf_grass_png = "texture.sf/grass";
    }
    public class Activity_btn_arrow
    {
        public const string BundleName = "activity_btn_arrow";
        public const string RES_activity_btn_arrow_png = "activity_btn_arrow";
    }
    public class Arts
    {
        public const string BundleName = "arts";
    }
    public class Battle_sf
    {
        public const string BundleName = "battle.sf";
        public const string RES_ArrowBody_prefab = "ArrowBody";
        public const string RES_ArrowHead_prefab = "ArrowHead";
        public const string RES_BattleView_prefab = "BattleView";
    }
    public class Game_scenes_sf
    {
        public const string BundleName = "game/scenes.sf";
        public const string RES_BaseScene_unity = "BaseScene";
        public const string RES_BattleView_unity = "BattleView";
    }
    public class Loading_sf
    {
        public const string BundleName = "loading.sf";
        public const string RES_BarLoading_prefab = "BarLoading";
        public const string RES_BaseLoading_prefab = "BaseLoading";
        public const string RES_effect_jpg = "effect";
        public const string RES_effect1_png = "effect1";
        public const string RES_GameMainView_prefab = "GameMainView";
    }
    public class Model_avatar_role_carrota
    {
        public const string BundleName = "model/avatar/role_carrota";
    }
    public class Model_avatar_role_carrota_sf
    {
        public const string BundleName = "model/avatar/role_carrota.sf";
        public const string RES_Carrot_BaseColor_png = "Carrot_BaseColor";
        public const string RES_Character_Carrot_prefab = "Character_Carrot";
        public const string RES_Role_CarrotA_Skin_prefab = "Role_CarrotA_Skin";
    }
    public class Pic_sf
    {
        public const string BundleName = "pic.sf";
        public const string RES_haipa_png = "haipa";
        public const string RES_haipa_normal_png = "haipa_normal";
        public const string RES_jusang_png = "jusang";
    }
    public class Pic_tree_sf
    {
        public const string BundleName = "pic/tree.sf";
        public const string RES_5101410_png = "5101410";
        public const string RES_5103524_png = "5103524";
        public const string RES_5104206_png = "5104206";
        public const string RES_5104309_png = "5104309";
        public const string RES_5104413_png = "5104413";
    }
    public class Ss_test
    {
        public const string BundleName = "ss/test";
        public const string RES_Test_prefab = "Test";
    }
    public class Texture_sf
    {
        public const string BundleName = "texture.sf";
        public const string RES_grass_png = "grass";
    }
}
