//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFramework.Statics
{
    
    public class SFResAssets
    {
        public const string Activity_btn_arrow_activity_btn_arrow_png = "activity_btn_arrow/activity_btn_arrow";
        public const string Game_app_battle_sf_ArrowBody_prefab = "game/app/battle.sf/ArrowBody";
        public const string Game_app_battle_sf_ArrowHead_prefab = "game/app/battle.sf/ArrowHead";
        public const string Game_app_battle_sf_BattleUIView_prefab = "game/app/battle.sf/BattleUIView";
        public const string Game_app_battle_sf_BattleView_unity = "game/app/battle.sf/BattleView";
        public const string Game_app_battle_sf_BezierCurve_prefab = "game/app/battle.sf/BezierCurve";
        public const string Game_app_battle_sf_Card_prefab = "game/app/battle.sf/Card";
        public const string Game_app_battle_sf_cardbg_png = "game/app/battle.sf/cardbg";
        public const string Game_scenes_sf_BaseScene_unity = "game/scenes.sf/BaseScene";
        public const string Game_turpworld_sf_TurpWorld_unity = "game/turpworld.sf/TurpWorld";
        public const string Game_turpworld_map_sf_dirt_prefab = "game/turpworld/map.sf/dirt";
        public const string Game_turpworld_map_sf_forrest_prefab = "game/turpworld/map.sf/forrest";
        public const string Game_turpworld_map_sf_meadow_prefab = "game/turpworld/map.sf/meadow";
        public const string Game_turpworld_map_sf_rock_prefab = "game/turpworld/map.sf/rock";
        public const string Loading_sf_BarLoading_prefab = "loading.sf/BarLoading";
        public const string Loading_sf_BaseLoading_prefab = "loading.sf/BaseLoading";
        public const string Loading_sf_effect_jpg = "loading.sf/effect";
        public const string Loading_sf_effect1_png = "loading.sf/effect1";
        public const string Loading_sf_GameMainView_prefab = "loading.sf/GameMainView";
        public const string Model_avatar_role_carrota_sf_Carrot_BaseColor_png = "model/avatar/role_carrota.sf/Carrot_BaseColor";
        public const string Model_avatar_role_carrota_sf_Character_Carrot_prefab = "model/avatar/role_carrota.sf/Character_Carrot";
        public const string Pic_sf_haipa_png = "pic.sf/haipa";
        public const string Pic_sf_haipa_normal_png = "pic.sf/haipa_normal";
        public const string Pic_sf_jusang_png = "pic.sf/jusang";
        public const string Pic_tree_sf_5101410_png = "pic/tree.sf/5101410";
        public const string Pic_tree_sf_5103524_png = "pic/tree.sf/5103524";
        public const string Pic_tree_sf_5104206_png = "pic/tree.sf/5104206";
        public const string Pic_tree_sf_5104309_png = "pic/tree.sf/5104309";
        public const string Pic_tree_sf_5104413_png = "pic/tree.sf/5104413";
        public const string Ss_test_Test_prefab = "ss/test/Test";
        public const string Texture_sf_grass_png = "texture.sf/grass";
    }
    public class Activity_btn_arrow
    {
        public const string BundleName = "activity_btn_arrow";
        public const string RES_activity_btn_arrow_png = "activity_btn_arrow";
    }
    public class Game_app_battle_sf
    {
        public const string BundleName = "game/app/battle.sf";
        public const string RES_ArrowBody_prefab = "ArrowBody";
        public const string RES_ArrowHead_prefab = "ArrowHead";
        public const string RES_BattleUIView_prefab = "BattleUIView";
        public const string RES_BattleView_unity = "BattleView";
        public const string RES_BezierCurve_prefab = "BezierCurve";
        public const string RES_Card_prefab = "Card";
        public const string RES_cardbg_png = "cardbg";
    }
    public class Game_scenes_sf
    {
        public const string BundleName = "game/scenes.sf";
        public const string RES_BaseScene_unity = "BaseScene";
    }
    public class Game_turpworld
    {
        public const string BundleName = "game/turpworld";
    }
    public class Game_turpworld_sf
    {
        public const string BundleName = "game/turpworld.sf";
        public const string RES_TurpWorld_unity = "TurpWorld";
    }
    public class Game_turpworld_map_sf
    {
        public const string BundleName = "game/turpworld/map.sf";
        public const string RES_dirt_prefab = "dirt";
        public const string RES_forrest_prefab = "forrest";
        public const string RES_meadow_prefab = "meadow";
        public const string RES_rock_prefab = "rock";
    }
    public class Game_turpworld_scene_sf
    {
        public const string BundleName = "game/turpworld/scene.sf";
    }
    public class Loading_sf
    {
        public const string BundleName = "loading.sf";
        public const string RES_BarLoading_prefab = "BarLoading";
        public const string RES_BaseLoading_prefab = "BaseLoading";
        public const string RES_effect_jpg = "effect";
        public const string RES_effect1_png = "effect1";
        public const string RES_GameMainView_prefab = "GameMainView";
    }
    public class Model_avatar_role_carrota_sf
    {
        public const string BundleName = "model/avatar/role_carrota.sf";
        public const string RES_Carrot_BaseColor_png = "Carrot_BaseColor";
        public const string RES_Character_Carrot_prefab = "Character_Carrot";
    }
    public class Pic_sf
    {
        public const string BundleName = "pic.sf";
        public const string RES_haipa_png = "haipa";
        public const string RES_haipa_normal_png = "haipa_normal";
        public const string RES_jusang_png = "jusang";
    }
    public class Pic_tree_sf
    {
        public const string BundleName = "pic/tree.sf";
        public const string RES_5101410_png = "5101410";
        public const string RES_5103524_png = "5103524";
        public const string RES_5104206_png = "5104206";
        public const string RES_5104309_png = "5104309";
        public const string RES_5104413_png = "5104413";
    }
    public class Ss_test
    {
        public const string BundleName = "ss/test";
        public const string RES_Test_prefab = "Test";
    }
    public class Texture_sf
    {
        public const string BundleName = "texture.sf";
        public const string RES_grass_png = "grass";
    }
}
