//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAssetsBundle
{
    
    public class Activity_btn_arrow
    {
        public const string BundleName = "activity_btn_arrow";
        public const string activity_btn_arrow = "activity_btn_arrow";
    }
    public class Arts
    {
        public const string BundleName = "arts";
    }
    public class Battle_sf
    {
        public const string BundleName = "battle.sf";
        public const string ArrowBody = "ArrowBody";
        public const string ArrowHead = "ArrowHead";
        public const string BattleView = "BattleView";
    }
    public class Effect_sf
    {
        public const string BundleName = "effect.sf";
        public const string FlashCard = "FlashCard";
        public const string FlashCard1 = "FlashCard1";
    }
    public class Loading_sf
    {
        public const string BundleName = "loading.sf";
        public const string BarLoading = "BarLoading";
        public const string BarLoadingEnd = "BarLoadingEnd";
        public const string BarLoadingStart = "BarLoadingStart";
        public const string BaseLoading = "BaseLoading";
        public const string effect = "effect";
        public const string effect1 = "effect1";
        public const string GameMainView = "GameMainView";
        public const string LoadingEnd = "LoadingEnd";
        public const string LoadingStart = "LoadingStart";
    }
    public class Modelavatar_sf
    {
        public const string BundleName = "model/avatar.sf";
        public const string Role_CarrotA_Appearance = "Role_CarrotA_Appearance";
        public const string Role_CarrotA_EatingIdle = "Role_CarrotA_EatingIdle";
        public const string Role_CarrotA_falldown = "Role_CarrotA_falldown";
        public const string Role_CarrotA_Feedback = "Role_CarrotA_Feedback";
        public const string Role_CarrotA_happy02 = "Role_CarrotA_happy02";
        public const string Role_CarrotA_retreat = "Role_CarrotA_retreat";
        public const string Role_CarrotA_Story_Angry = "Role_CarrotA_Story_Angry";
        public const string Role_CarrotA_Story_Depressed = "Role_CarrotA_Story_Depressed";
        public const string Role_CarrotA_Story_Feedback = "Role_CarrotA_Story_Feedback";
        public const string Role_CarrotA_Story_Happy = "Role_CarrotA_Story_Happy";
        public const string Role_CarrotA_Story_Run = "Role_CarrotA_Story_Run";
        public const string Role_CarrotA_Story_Serious = "Role_CarrotA_Story_Serious";
        public const string Role_CarrotA_Story_Surprised = "Role_CarrotA_Story_Surprised";
        public const string Role_CarrotA_Story_Talk01 = "Role_CarrotA_Story_Talk01";
        public const string Role_CarrotA_Story_Talk02 = "Role_CarrotA_Story_Talk02";
        public const string Role_CarrotA_Story_Walk = "Role_CarrotA_Story_Walk";
        public const string Role_CarrotA_work_stone = "Role_CarrotA_work_stone";
        public const string Role_CarrotA_work_wood = "Role_CarrotA_work_wood";
        public const string Role_CarrotA_Attack = "Role_CarrotA_Attack";
        public const string Role_CarrotA_CasualState = "Role_CarrotA_CasualState";
        public const string Role_CarrotA_eat = "Role_CarrotA_eat";
        public const string Role_CarrotA_Hit = "Role_CarrotA_Hit";
        public const string Role_CarrotA_IdleState = "Role_CarrotA_IdleState";
        public const string Role_CarrotA_MoveState = "Role_CarrotA_MoveState";
        public const string Role_CarrotA_Skill = "Role_CarrotA_Skill";
        public const string Role_CarrotA_vertigo = "Role_CarrotA_vertigo";
        public const string Role_CarrotA_work_Cave = "Role_CarrotA_work_Cave";
        public const string Role_CarrotA_yuanditiao = "Role_CarrotA_yuanditiao";
        public const string Carrot_BaseColor = "Carrot_BaseColor";
        public const string Role = "Role";
        public const string Role_CarrotA = "Role_CarrotA";
        public const string Role_CarrotA_Skin = "Role_CarrotA_Skin";
    }
    public class Modelmaterial_sf
    {
        public const string BundleName = "model/material.sf";
        public const string DirectionDissolve = "DirectionDissolve";
        public const string HoloGraphic = "HoloGraphic";
        public const string RimPower = "RimPower";
        public const string Role = "Role";
        public const string RoleBlinn = "RoleBlinn";
        public const string RoleBlinnPhong = "RoleBlinnPhong";
        public const string SimpleDissolve = "SimpleDissolve";
        public const string Test = "Test";
    }
    public class Pic_sf
    {
        public const string BundleName = "pic.sf";
        public const string haipa = "haipa";
        public const string haipa_normal = "haipa_normal";
        public const string jusang = "jusang";
    }
    public class Scenesbasescene
    {
        public const string BundleName = "scenes/basescene";
        public const string BaseScene = "BaseScene";
    }
    public class Sstest
    {
        public const string BundleName = "ss/test";
        public const string Test = "Test";
    }
}
