# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Card_Base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43\x61rd_Base.proto\x12\tCard_Base\"S\n\tCard_Base\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07quality\x18\x03 \x01(\x11\x12\x0c\n\x04Icon\x18\x04 \x01(\t\x12\r\n\x05Story\x18\x05 \x01(\t\"\xb6\x01\n\x0f\x43\x61rd_Base_datas\x12\x38\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32\'.Card_Base.Card_Base_datas.DatamapEntry\x12#\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x14.Card_Base.Card_Base\x1a\x44\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.Card_Base.Card_Base:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Card_Base_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARD_BASE_DATAS_DATAMAPENTRY._options = None
  _CARD_BASE_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_CARD_BASE']._serialized_start=30
  _globals['_CARD_BASE']._serialized_end=113
  _globals['_CARD_BASE_DATAS']._serialized_start=116
  _globals['_CARD_BASE_DATAS']._serialized_end=298
  _globals['_CARD_BASE_DATAS_DATAMAPENTRY']._serialized_start=230
  _globals['_CARD_BASE_DATAS_DATAMAPENTRY']._serialized_end=298
# @@protoc_insertion_point(module_scope)
