# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: character_Base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63haracter_Base.proto\x12\x0e\x63haracter_Base\"y\n\x0e\x63haracter_Base\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07quality\x18\x03 \x01(\x11\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\x11\x12\x0e\n\x06\x63\x61reer\x18\x05 \x01(\x11\x12\x0c\n\x04Icon\x18\x06 \x01(\t\x12\r\n\x05Story\x18\x07 \x01(\t\"\xd9\x01\n\x14\x63haracter_Base_datas\x12\x42\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32\x31.character_Base.character_Base_datas.DatamapEntry\x12-\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x1e.character_Base.character_Base\x1aN\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.character_Base.character_Base:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'character_Base_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHARACTER_BASE_DATAS_DATAMAPENTRY._options = None
  _CHARACTER_BASE_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_CHARACTER_BASE']._serialized_start=40
  _globals['_CHARACTER_BASE']._serialized_end=161
  _globals['_CHARACTER_BASE_DATAS']._serialized_start=164
  _globals['_CHARACTER_BASE_DATAS']._serialized_end=381
  _globals['_CHARACTER_BASE_DATAS_DATAMAPENTRY']._serialized_start=303
  _globals['_CHARACTER_BASE_DATAS_DATAMAPENTRY']._serialized_end=381
# @@protoc_insertion_point(module_scope)
