# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10test_event.proto\x12\ntest_event\"\x93\x02\n\ntest_event\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x19\n\x11UnlockPlayerLevel\x18\x02 \x01(\x03\x12\x0c\n\x04Type\x18\x03 \x01(\r\x12\x13\n\x0b\x43haracterID\x18\x04 \x01(\x04\x12\r\n\x05Sort1\x18\x05 \x01(\x11\x12\r\n\x05Sort2\x18\x06 \x01(\x12\x12\r\n\x05Sort3\x18\x07 \x01(\x07\x12\r\n\x05Sort4\x18\x08 \x01(\x06\x12\r\n\x05Sort5\x18\t \x01(\x0f\x12\r\n\x05Sort6\x18\n \x01(\x10\x12\x0c\n\x04Name\x18\x0b \x01(\t\x12\x11\n\tIntroduce\x18\x0c \x01(\x08\x12\x0f\n\x07JumpKey\x18\r \x01(\x02\x12\x12\n\nJumpParams\x18\x0e \x01(\x01\x12\x1b\n\x13ReminderInformation\x18\x0f \x03(\r\"\xbd\x01\n\x10test_event_datas\x12:\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32).test_event.test_event_datas.DatamapEntry\x12%\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x16.test_event.test_event\x1a\x46\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.test_event.test_event:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEST_EVENT_DATAS_DATAMAPENTRY._options = None
  _TEST_EVENT_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_TEST_EVENT']._serialized_start=33
  _globals['_TEST_EVENT']._serialized_end=308
  _globals['_TEST_EVENT_DATAS']._serialized_start=311
  _globals['_TEST_EVENT_DATAS']._serialized_end=500
  _globals['_TEST_EVENT_DATAS_DATAMAPENTRY']._serialized_start=430
  _globals['_TEST_EVENT_DATAS_DATAMAPENTRY']._serialized_end=500
# @@protoc_insertion_point(module_scope)
