// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TestEvent {

  /// <summary>Holder for reflection information generated from test_event.proto</summary>
  public static partial class TestEventReflection {

    #region Descriptor
    /// <summary>File descriptor for test_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChB0ZXN0X2V2ZW50LnByb3RvEgp0ZXN0X2V2ZW50IpMCCgp0ZXN0X2V2ZW50",
            "EgoKAklEGAEgASgFEhkKEVVubG9ja1BsYXllckxldmVsGAIgASgDEgwKBFR5",
            "cGUYAyABKA0SEwoLQ2hhcmFjdGVySUQYBCABKAQSDQoFU29ydDEYBSABKBES",
            "DQoFU29ydDIYBiABKBISDQoFU29ydDMYByABKAcSDQoFU29ydDQYCCABKAYS",
            "DQoFU29ydDUYCSABKA8SDQoFU29ydDYYCiABKBASDAoETmFtZRgLIAEoCRIR",
            "CglJbnRyb2R1Y2UYDCABKAgSDwoHSnVtcEtleRgNIAEoAhISCgpKdW1wUGFy",
            "YW1zGA4gASgBEhsKE1JlbWluZGVySW5mb3JtYXRpb24YDyADKA0ivQEKEHRl",
            "c3RfZXZlbnRfZGF0YXMSOgoHZGF0YW1hcBgBIAMoCzIpLnRlc3RfZXZlbnQu",
            "dGVzdF9ldmVudF9kYXRhcy5EYXRhbWFwRW50cnkSJQoFZGF0YXMYAiADKAsy",
            "Fi50ZXN0X2V2ZW50LnRlc3RfZXZlbnQaRgoMRGF0YW1hcEVudHJ5EgsKA2tl",
            "eRgBIAEoBRIlCgV2YWx1ZRgCIAEoCzIWLnRlc3RfZXZlbnQudGVzdF9ldmVu",
            "dDoCOAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TestEvent.test_event), global::TestEvent.test_event.Parser, new[]{ "ID", "UnlockPlayerLevel", "Type", "CharacterID", "Sort1", "Sort2", "Sort3", "Sort4", "Sort5", "Sort6", "Name", "Introduce", "JumpKey", "JumpParams", "ReminderInformation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TestEvent.test_event_datas), global::TestEvent.test_event_datas.Parser, new[]{ "Datamap", "Datas" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class test_event : pb::IMessage<test_event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<test_event> _parser = new pb::MessageParser<test_event>(() => new test_event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<test_event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TestEvent.TestEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public test_event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public test_event(test_event other) : this() {
      iD_ = other.iD_;
      unlockPlayerLevel_ = other.unlockPlayerLevel_;
      type_ = other.type_;
      characterID_ = other.characterID_;
      sort1_ = other.sort1_;
      sort2_ = other.sort2_;
      sort3_ = other.sort3_;
      sort4_ = other.sort4_;
      sort5_ = other.sort5_;
      sort6_ = other.sort6_;
      name_ = other.name_;
      introduce_ = other.introduce_;
      jumpKey_ = other.jumpKey_;
      jumpParams_ = other.jumpParams_;
      reminderInformation_ = other.reminderInformation_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public test_event Clone() {
      return new test_event(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private int iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "UnlockPlayerLevel" field.</summary>
    public const int UnlockPlayerLevelFieldNumber = 2;
    private long unlockPlayerLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UnlockPlayerLevel {
      get { return unlockPlayerLevel_; }
      set {
        unlockPlayerLevel_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 3;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "CharacterID" field.</summary>
    public const int CharacterIDFieldNumber = 4;
    private ulong characterID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CharacterID {
      get { return characterID_; }
      set {
        characterID_ = value;
      }
    }

    /// <summary>Field number for the "Sort1" field.</summary>
    public const int Sort1FieldNumber = 5;
    private int sort1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sort1 {
      get { return sort1_; }
      set {
        sort1_ = value;
      }
    }

    /// <summary>Field number for the "Sort2" field.</summary>
    public const int Sort2FieldNumber = 6;
    private long sort2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sort2 {
      get { return sort2_; }
      set {
        sort2_ = value;
      }
    }

    /// <summary>Field number for the "Sort3" field.</summary>
    public const int Sort3FieldNumber = 7;
    private uint sort3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sort3 {
      get { return sort3_; }
      set {
        sort3_ = value;
      }
    }

    /// <summary>Field number for the "Sort4" field.</summary>
    public const int Sort4FieldNumber = 8;
    private ulong sort4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Sort4 {
      get { return sort4_; }
      set {
        sort4_ = value;
      }
    }

    /// <summary>Field number for the "Sort5" field.</summary>
    public const int Sort5FieldNumber = 9;
    private int sort5_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sort5 {
      get { return sort5_; }
      set {
        sort5_ = value;
      }
    }

    /// <summary>Field number for the "Sort6" field.</summary>
    public const int Sort6FieldNumber = 10;
    private long sort6_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sort6 {
      get { return sort6_; }
      set {
        sort6_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 11;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Introduce" field.</summary>
    public const int IntroduceFieldNumber = 12;
    private bool introduce_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Introduce {
      get { return introduce_; }
      set {
        introduce_ = value;
      }
    }

    /// <summary>Field number for the "JumpKey" field.</summary>
    public const int JumpKeyFieldNumber = 13;
    private float jumpKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float JumpKey {
      get { return jumpKey_; }
      set {
        jumpKey_ = value;
      }
    }

    /// <summary>Field number for the "JumpParams" field.</summary>
    public const int JumpParamsFieldNumber = 14;
    private double jumpParams_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double JumpParams {
      get { return jumpParams_; }
      set {
        jumpParams_ = value;
      }
    }

    /// <summary>Field number for the "ReminderInformation" field.</summary>
    public const int ReminderInformationFieldNumber = 15;
    private static readonly pb::FieldCodec<uint> _repeated_reminderInformation_codec
        = pb::FieldCodec.ForUInt32(122);
    private readonly pbc::RepeatedField<uint> reminderInformation_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> ReminderInformation {
      get { return reminderInformation_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as test_event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(test_event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (UnlockPlayerLevel != other.UnlockPlayerLevel) return false;
      if (Type != other.Type) return false;
      if (CharacterID != other.CharacterID) return false;
      if (Sort1 != other.Sort1) return false;
      if (Sort2 != other.Sort2) return false;
      if (Sort3 != other.Sort3) return false;
      if (Sort4 != other.Sort4) return false;
      if (Sort5 != other.Sort5) return false;
      if (Sort6 != other.Sort6) return false;
      if (Name != other.Name) return false;
      if (Introduce != other.Introduce) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(JumpKey, other.JumpKey)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(JumpParams, other.JumpParams)) return false;
      if(!reminderInformation_.Equals(other.reminderInformation_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0) hash ^= ID.GetHashCode();
      if (UnlockPlayerLevel != 0L) hash ^= UnlockPlayerLevel.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (CharacterID != 0UL) hash ^= CharacterID.GetHashCode();
      if (Sort1 != 0) hash ^= Sort1.GetHashCode();
      if (Sort2 != 0L) hash ^= Sort2.GetHashCode();
      if (Sort3 != 0) hash ^= Sort3.GetHashCode();
      if (Sort4 != 0UL) hash ^= Sort4.GetHashCode();
      if (Sort5 != 0) hash ^= Sort5.GetHashCode();
      if (Sort6 != 0L) hash ^= Sort6.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Introduce != false) hash ^= Introduce.GetHashCode();
      if (JumpKey != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(JumpKey);
      if (JumpParams != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(JumpParams);
      hash ^= reminderInformation_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      if (UnlockPlayerLevel != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UnlockPlayerLevel);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Type);
      }
      if (CharacterID != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(CharacterID);
      }
      if (Sort1 != 0) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sort1);
      }
      if (Sort2 != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sort2);
      }
      if (Sort3 != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Sort3);
      }
      if (Sort4 != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(Sort4);
      }
      if (Sort5 != 0) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sort5);
      }
      if (Sort6 != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sort6);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Name);
      }
      if (Introduce != false) {
        output.WriteRawTag(96);
        output.WriteBool(Introduce);
      }
      if (JumpKey != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(JumpKey);
      }
      if (JumpParams != 0D) {
        output.WriteRawTag(113);
        output.WriteDouble(JumpParams);
      }
      reminderInformation_.WriteTo(output, _repeated_reminderInformation_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      if (UnlockPlayerLevel != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UnlockPlayerLevel);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Type);
      }
      if (CharacterID != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(CharacterID);
      }
      if (Sort1 != 0) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sort1);
      }
      if (Sort2 != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sort2);
      }
      if (Sort3 != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Sort3);
      }
      if (Sort4 != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(Sort4);
      }
      if (Sort5 != 0) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sort5);
      }
      if (Sort6 != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sort6);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Name);
      }
      if (Introduce != false) {
        output.WriteRawTag(96);
        output.WriteBool(Introduce);
      }
      if (JumpKey != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(JumpKey);
      }
      if (JumpParams != 0D) {
        output.WriteRawTag(113);
        output.WriteDouble(JumpParams);
      }
      reminderInformation_.WriteTo(ref output, _repeated_reminderInformation_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
      }
      if (UnlockPlayerLevel != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UnlockPlayerLevel);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (CharacterID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CharacterID);
      }
      if (Sort1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Sort1);
      }
      if (Sort2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Sort2);
      }
      if (Sort3 != 0) {
        size += 1 + 4;
      }
      if (Sort4 != 0UL) {
        size += 1 + 8;
      }
      if (Sort5 != 0) {
        size += 1 + 4;
      }
      if (Sort6 != 0L) {
        size += 1 + 8;
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Introduce != false) {
        size += 1 + 1;
      }
      if (JumpKey != 0F) {
        size += 1 + 4;
      }
      if (JumpParams != 0D) {
        size += 1 + 8;
      }
      size += reminderInformation_.CalculateSize(_repeated_reminderInformation_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(test_event other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      if (other.UnlockPlayerLevel != 0L) {
        UnlockPlayerLevel = other.UnlockPlayerLevel;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.CharacterID != 0UL) {
        CharacterID = other.CharacterID;
      }
      if (other.Sort1 != 0) {
        Sort1 = other.Sort1;
      }
      if (other.Sort2 != 0L) {
        Sort2 = other.Sort2;
      }
      if (other.Sort3 != 0) {
        Sort3 = other.Sort3;
      }
      if (other.Sort4 != 0UL) {
        Sort4 = other.Sort4;
      }
      if (other.Sort5 != 0) {
        Sort5 = other.Sort5;
      }
      if (other.Sort6 != 0L) {
        Sort6 = other.Sort6;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Introduce != false) {
        Introduce = other.Introduce;
      }
      if (other.JumpKey != 0F) {
        JumpKey = other.JumpKey;
      }
      if (other.JumpParams != 0D) {
        JumpParams = other.JumpParams;
      }
      reminderInformation_.Add(other.reminderInformation_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 16: {
            UnlockPlayerLevel = input.ReadInt64();
            break;
          }
          case 24: {
            Type = input.ReadUInt32();
            break;
          }
          case 32: {
            CharacterID = input.ReadUInt64();
            break;
          }
          case 40: {
            Sort1 = input.ReadSInt32();
            break;
          }
          case 48: {
            Sort2 = input.ReadSInt64();
            break;
          }
          case 61: {
            Sort3 = input.ReadFixed32();
            break;
          }
          case 65: {
            Sort4 = input.ReadFixed64();
            break;
          }
          case 77: {
            Sort5 = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sort6 = input.ReadSFixed64();
            break;
          }
          case 90: {
            Name = input.ReadString();
            break;
          }
          case 96: {
            Introduce = input.ReadBool();
            break;
          }
          case 109: {
            JumpKey = input.ReadFloat();
            break;
          }
          case 113: {
            JumpParams = input.ReadDouble();
            break;
          }
          case 122:
          case 120: {
            reminderInformation_.AddEntriesFrom(input, _repeated_reminderInformation_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 16: {
            UnlockPlayerLevel = input.ReadInt64();
            break;
          }
          case 24: {
            Type = input.ReadUInt32();
            break;
          }
          case 32: {
            CharacterID = input.ReadUInt64();
            break;
          }
          case 40: {
            Sort1 = input.ReadSInt32();
            break;
          }
          case 48: {
            Sort2 = input.ReadSInt64();
            break;
          }
          case 61: {
            Sort3 = input.ReadFixed32();
            break;
          }
          case 65: {
            Sort4 = input.ReadFixed64();
            break;
          }
          case 77: {
            Sort5 = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sort6 = input.ReadSFixed64();
            break;
          }
          case 90: {
            Name = input.ReadString();
            break;
          }
          case 96: {
            Introduce = input.ReadBool();
            break;
          }
          case 109: {
            JumpKey = input.ReadFloat();
            break;
          }
          case 113: {
            JumpParams = input.ReadDouble();
            break;
          }
          case 122:
          case 120: {
            reminderInformation_.AddEntriesFrom(ref input, _repeated_reminderInformation_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class test_event_datas : pb::IMessage<test_event_datas>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<test_event_datas> _parser = new pb::MessageParser<test_event_datas>(() => new test_event_datas());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<test_event_datas> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TestEvent.TestEventReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public test_event_datas() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public test_event_datas(test_event_datas other) : this() {
      datamap_ = other.datamap_.Clone();
      datas_ = other.datas_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public test_event_datas Clone() {
      return new test_event_datas(this);
    }

    /// <summary>Field number for the "datamap" field.</summary>
    public const int DatamapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::TestEvent.test_event>.Codec _map_datamap_codec
        = new pbc::MapField<int, global::TestEvent.test_event>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::TestEvent.test_event.Parser), 10);
    private readonly pbc::MapField<int, global::TestEvent.test_event> datamap_ = new pbc::MapField<int, global::TestEvent.test_event>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::TestEvent.test_event> Datamap {
      get { return datamap_; }
    }

    /// <summary>Field number for the "datas" field.</summary>
    public const int DatasFieldNumber = 2;
    private static readonly pb::FieldCodec<global::TestEvent.test_event> _repeated_datas_codec
        = pb::FieldCodec.ForMessage(18, global::TestEvent.test_event.Parser);
    private readonly pbc::RepeatedField<global::TestEvent.test_event> datas_ = new pbc::RepeatedField<global::TestEvent.test_event>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TestEvent.test_event> Datas {
      get { return datas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as test_event_datas);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(test_event_datas other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Datamap.Equals(other.Datamap)) return false;
      if(!datas_.Equals(other.datas_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Datamap.GetHashCode();
      hash ^= datas_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      datamap_.WriteTo(output, _map_datamap_codec);
      datas_.WriteTo(output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      datamap_.WriteTo(ref output, _map_datamap_codec);
      datas_.WriteTo(ref output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += datamap_.CalculateSize(_map_datamap_codec);
      size += datas_.CalculateSize(_repeated_datas_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(test_event_datas other) {
      if (other == null) {
        return;
      }
      datamap_.MergeFrom(other.datamap_);
      datas_.Add(other.datas_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            datamap_.AddEntriesFrom(input, _map_datamap_codec);
            break;
          }
          case 18: {
            datas_.AddEntriesFrom(input, _repeated_datas_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            datamap_.AddEntriesFrom(ref input, _map_datamap_codec);
            break;
          }
          case 18: {
            datas_.AddEntriesFrom(ref input, _repeated_datas_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
